[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spark-pyspark-test-dheeraj"
version = "0.1.0"
description = "PySpark project with pytest setup"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyspark"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
